name: Build and Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: igordcsouza/github-action-get-branch-name@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log
        env:
          CONTEXT: ${{ github.ref != 'dev' && format('{{{0}-{1}-{2}}}', 'review', env.BRANCH_NAME, github.run_id) }}
        run: echo "$CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: dist
          TARGET_FOLDER: ${{ github.ref != 'dev' && format('{{{0}-{1}-{2}}}', 'review', github.head_ref, github.run_id) }}
          CLEAN: false
          SINGLE_COMMIT: true
