name: Remove Preview Deploy

on:
  pull_request:
    types: [closed]

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - uses: igordcsouza/github-action-get-branch-name@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log
        run: echo $TARGET_FOLDER
        env:
          TARGET_FOLDER: ${{ format('{0}-{1}', 'review', env.BRANCH_NAME) }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove folder
        run: rm -rf "$TARGET_FOLDER"
        env:
          TARGET_FOLDER: ${{ format('{0}-{1}', 'review', env.BRANCH_NAME) }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: .
          CLEAN: false
          SINGLE_COMMIT: true
